# coding: utf-8

"""
    attachmentAV

    An SDK to integrate virus and malware scan capabilities into Python applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachmentav.api.attachment_av_api import AttachmentAVApi


class TestAttachmentAVApi(unittest.TestCase):
    """AttachmentAVApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AttachmentAVApi()

    def tearDown(self) -> None:
        pass

    def test_scan_async_download_post(self) -> None:
        """Test case for scan_async_download_post

        """
        pass

    def test_scan_async_result_get(self) -> None:
        """Test case for scan_async_result_get

        """
        pass

    def test_scan_async_s3_post(self) -> None:
        """Test case for scan_async_s3_post

        """
        pass

    def test_scan_sync_binary_post(self) -> None:
        """Test case for scan_sync_binary_post

        """
        pass

    def test_scan_sync_download_post(self) -> None:
        """Test case for scan_sync_download_post

        """
        pass

    def test_scan_sync_s3_post(self) -> None:
        """Test case for scan_sync_s3_post

        """
        pass

    def test_usage_get(self) -> None:
        """Test case for usage_get

        """
        pass

    def test_whoami_get(self) -> None:
        """Test case for whoami_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
