# coding: utf-8

"""
    attachmentAV

    An SDK to integrate virus and malware scan capabilities into Python applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachmentav.models.usage_quota import UsageQuota

class TestUsageQuota(unittest.TestCase):
    """UsageQuota unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageQuota:
        """Test UsageQuota
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageQuota`
        """
        model = UsageQuota()
        if include_optional:
            return UsageQuota(
                limit = 1.337,
                period = ''
            )
        else:
            return UsageQuota(
                limit = 1.337,
                period = '',
        )
        """

    def testUsageQuota(self):
        """Test UsageQuota"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
