# coding: utf-8

"""
    attachmentAV

    An SDK to integrate virus and malware scan capabilities into Python applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachmentav.models.async_s3_scan_request import AsyncS3ScanRequest

class TestAsyncS3ScanRequest(unittest.TestCase):
    """AsyncS3ScanRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AsyncS3ScanRequest:
        """Test AsyncS3ScanRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AsyncS3ScanRequest`
        """
        model = AsyncS3ScanRequest()
        if include_optional:
            return AsyncS3ScanRequest(
                bucket = '',
                key = '',
                version = '',
                callback_url = 'https://rZ# \\vRsp&$ARjbhJkfC< ^&T\\{<\'cs)#<`206.254.11.254',
                callback_headers = {
                    'key' : ''
                    },
                trace_id = '',
                custom_data = ''
            )
        else:
            return AsyncS3ScanRequest(
                bucket = '',
                key = '',
        )
        """

    def testAsyncS3ScanRequest(self):
        """Test AsyncS3ScanRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
