# coding: utf-8

"""
    attachmentAV

    An SDK to integrate virus and malware scan capabilities into Python applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from attachmentav.models.callback_failures import CallbackFailures

class TestCallbackFailures(unittest.TestCase):
    """CallbackFailures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CallbackFailures:
        """Test CallbackFailures
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallbackFailures`
        """
        model = CallbackFailures()
        if include_optional:
            return CallbackFailures(
                failures = [
                    attachmentav.models.callback_failure.CallbackFailure(
                        id = '', 
                        time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        download_url = '', 
                        callback_url = '', 
                        error_json = '', )
                    ],
                next_cursor = ''
            )
        else:
            return CallbackFailures(
                failures = [
                    attachmentav.models.callback_failure.CallbackFailure(
                        id = '', 
                        time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        download_url = '', 
                        callback_url = '', 
                        error_json = '', )
                    ],
        )
        """

    def testCallbackFailures(self):
        """Test CallbackFailures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
