# coding: utf-8

# flake8: noqa

"""
    attachmentAV

    An SDK to integrate virus and malware scan capabilities into Python applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.4.0"

# Define package exports
__all__ = [
    "AttachmentAVApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AsyncDownloadScanRequest",
    "AsyncS3ScanRequest",
    "ScanResult",
    "SyncDownloadScanRequest",
    "SyncS3ScanRequest",
    "Usage",
    "UsageQuota",
    "Whoami",
]

# import apis into sdk package
from attachmentav.api.attachment_av_api import AttachmentAVApi as AttachmentAVApi

# import ApiClient
from attachmentav.api_response import ApiResponse as ApiResponse
from attachmentav.api_client import ApiClient as ApiClient
from attachmentav.configuration import Configuration as Configuration
from attachmentav.exceptions import OpenApiException as OpenApiException
from attachmentav.exceptions import ApiTypeError as ApiTypeError
from attachmentav.exceptions import ApiValueError as ApiValueError
from attachmentav.exceptions import ApiKeyError as ApiKeyError
from attachmentav.exceptions import ApiAttributeError as ApiAttributeError
from attachmentav.exceptions import ApiException as ApiException

# import models into sdk package
from attachmentav.models.async_download_scan_request import AsyncDownloadScanRequest as AsyncDownloadScanRequest
from attachmentav.models.async_s3_scan_request import AsyncS3ScanRequest as AsyncS3ScanRequest
from attachmentav.models.scan_result import ScanResult as ScanResult
from attachmentav.models.sync_download_scan_request import SyncDownloadScanRequest as SyncDownloadScanRequest
from attachmentav.models.sync_s3_scan_request import SyncS3ScanRequest as SyncS3ScanRequest
from attachmentav.models.usage import Usage as Usage
from attachmentav.models.usage_quota import UsageQuota as UsageQuota
from attachmentav.models.whoami import Whoami as Whoami

