# coding: utf-8

# flake8: noqa
"""
    attachmentAV

    An SDK to integrate virus and malware scan capabilities into Python applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from attachmentav.models.async_download_scan_request import AsyncDownloadScanRequest
    from attachmentav.models.async_s3_scan_request import AsyncS3ScanRequest
    from attachmentav.models.scan_result import ScanResult
    from attachmentav.models.sync_download_scan_request import SyncDownloadScanRequest
    from attachmentav.models.sync_s3_scan_request import SyncS3ScanRequest
    from attachmentav.models.usage_result import UsageResult
    from attachmentav.models.usage_result_quota import UsageResultQuota
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from attachmentav.models.async_download_scan_request import AsyncDownloadScanRequest
from attachmentav.models.async_s3_scan_request import AsyncS3ScanRequest
from attachmentav.models.scan_result import ScanResult
from attachmentav.models.sync_download_scan_request import SyncDownloadScanRequest
from attachmentav.models.sync_s3_scan_request import SyncS3ScanRequest
from attachmentav.models.usage_result import UsageResult
from attachmentav.models.usage_result_quota import UsageResultQuota

""",
            name=__name__,
            doc=__doc__,
        )
    )
